/*
 * Nicholas Dry
 * Copyright 2016
 */
package htmlgenerator;

import java.io.*;
import java.util.*;

/**
 *
 * @author nicholasdry
 */
public class HTMLGeneratorGUI extends javax.swing.JFrame {

    /**
     * Creates new form HTMLGen
     */

    public static HTMLElements html = new HTMLElements();


    public HTMLGeneratorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpWindow = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        addCSSWindow = new javax.swing.JFrame();
        cssFileName = new javax.swing.JLabel();
        cssFileField = new javax.swing.JTextField();
        cssAddButton = new javax.swing.JButton();
        addJSWindow = new javax.swing.JFrame();
        jsFileName = new javax.swing.JLabel();
        jsFileField = new javax.swing.JTextField();
        jsAddButton = new javax.swing.JButton();
        paragraphScollPane = new javax.swing.JScrollPane();
        paragraphTextField = new javax.swing.JTextArea();
        titleText = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        headerText = new javax.swing.JLabel();
        headerTextField = new javax.swing.JTextField();
        paragraphText = new javax.swing.JLabel();
        footerText = new javax.swing.JLabel();
        footerTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        htmlFormatting = new javax.swing.JCheckBox();
        fileName = new javax.swing.JTextField();
        fileNameTag = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        fileNew = new javax.swing.JMenuItem();
        fileClose = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        addCSS = new javax.swing.JMenuItem();
        addJS = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        htmlTagGuide = new javax.swing.JMenuItem();

        helpWindow.setTitle("HTML Tags");
        helpWindow.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabel2.setText("Do I show now?");

        javax.swing.GroupLayout helpWindowLayout = new javax.swing.GroupLayout(helpWindow.getContentPane());
        helpWindow.getContentPane().setLayout(helpWindowLayout);
        helpWindowLayout.setHorizontalGroup(
            helpWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpWindowLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        helpWindowLayout.setVerticalGroup(
            helpWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, helpWindowLayout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(127, 127, 127))
        );

        addCSSWindow.setMinimumSize(new java.awt.Dimension(400, 150));

        cssFileName.setText("Enter Name of CSS File:");

        cssAddButton.setText("Link");
        cssAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cssAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCSSWindowLayout = new javax.swing.GroupLayout(addCSSWindow.getContentPane());
        addCSSWindow.getContentPane().setLayout(addCSSWindowLayout);
        addCSSWindowLayout.setHorizontalGroup(
            addCSSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCSSWindowLayout.createSequentialGroup()
                .addGroup(addCSSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCSSWindowLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cssFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cssFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCSSWindowLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(cssAddButton)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        addCSSWindowLayout.setVerticalGroup(
            addCSSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCSSWindowLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(addCSSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cssFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cssFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cssAddButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        addJSWindow.setMinimumSize(new java.awt.Dimension(400, 150));

        jsFileName.setText("Enter Name of JS File:");

        jsAddButton.setText("Link");
        jsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addJSWindowLayout = new javax.swing.GroupLayout(addJSWindow.getContentPane());
        addJSWindow.getContentPane().setLayout(addJSWindowLayout);
        addJSWindowLayout.setHorizontalGroup(
            addJSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJSWindowLayout.createSequentialGroup()
                .addGroup(addJSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJSWindowLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jsFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jsFileField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addJSWindowLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jsAddButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        addJSWindowLayout.setVerticalGroup(
            addJSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJSWindowLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(addJSWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsAddButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paragraphTextField.setColumns(20);
        paragraphTextField.setRows(5);
        paragraphScollPane.setViewportView(paragraphTextField);

        titleText.setText("Website Title");

        headerText.setText("Website Header");

        paragraphText.setText("Website Text");

        footerText.setText("Website Footer");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        htmlFormatting.setText("HTML Formatting");
        htmlFormatting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlFormattingActionPerformed(evt);
            }
        });

        fileNameTag.setText("File Name");

        file.setText("File");

        fileNew.setText("New");
        fileNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNewActionPerformed(evt);
            }
        });
        file.add(fileNew);

        fileClose.setText("Close");
        fileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileCloseActionPerformed(evt);
            }
        });
        file.add(fileClose);

        menuBar.add(file);

        edit.setText("Edit");

        addCSS.setText("Add CSS..");
        addCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCSSActionPerformed(evt);
            }
        });
        edit.add(addCSS);

        addJS.setText("Add JavaScript..");
        addJS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJSActionPerformed(evt);
            }
        });
        edit.add(addJS);

        menuBar.add(edit);

        help.setText("Help");

        htmlTagGuide.setText("HTML Tag Guide");
        htmlTagGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlTagGuideActionPerformed(evt);
            }
        });
        help.add(htmlTagGuide);

        menuBar.add(help);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileNameTag)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(htmlFormatting)
                    .addComponent(saveButton)
                    .addComponent(footerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(footerText)
                    .addComponent(paragraphScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paragraphText)
                    .addComponent(titleText)
                    .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerText))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {fileName, footerTextField, headerTextField, titleTextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headerText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(headerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paragraphText)
                .addGap(18, 18, 18)
                .addComponent(paragraphScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(htmlFormatting)
                .addGap(18, 18, 18)
                .addComponent(fileNameTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footerText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        html.setTitle(titleTextField.getText());
        html.setHeader(headerTextField.getText());
        html.setParagraph(paragraphTextField.getText());
        html.setFooter(footerTextField.getText());

        // Grabs the file name for the output
        String file = fileName.getText();
       
        // 
        if (htmlFormatting.isSelected()) {
            try {
                PrintWriter output = new PrintWriter(file, "UTF-8");
                exportHTMLFormatted(output);
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
        } else {
            try {
                PrintWriter output = new PrintWriter(file, "UTF-8");
                exportHTML(output);
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void htmlFormattingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlFormattingActionPerformed
        
    }//GEN-LAST:event_htmlFormattingActionPerformed

    private void fileNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNewActionPerformed
        
        titleTextField.setText("");
        headerTextField.setText("");
        paragraphTextField.setText("");
        fileName.setText("");
        footerTextField.setText("");
    }//GEN-LAST:event_fileNewActionPerformed

    private void fileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_fileCloseActionPerformed

    private void htmlTagGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlTagGuideActionPerformed
        helpWindow.setVisible(true);
    }//GEN-LAST:event_htmlTagGuideActionPerformed

    private void addCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCSSActionPerformed
        
        addCSSWindow.setVisible(true);
        
    }//GEN-LAST:event_addCSSActionPerformed

    private void cssAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cssAddButtonActionPerformed
        
        
        html.setCSS(cssFileName.getText());
        this.setVisible(false);
        
    }//GEN-LAST:event_cssAddButtonActionPerformed

    private void jsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsAddButtonActionPerformed
        
        html.setJavaScript(jsFileName.getText());
        this.setVisible(false);
        
    }//GEN-LAST:event_jsAddButtonActionPerformed

    private void addJSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJSActionPerformed
        
        addJSWindow.setVisible(true);
        
    }//GEN-LAST:event_addJSActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HTMLGeneratorGUI().setVisible(true);
            }
        });

    }

    private static void exportHTML(PrintWriter output) {

		output.println("<html>");
		output.println();

		// adds in copyright info
		output.println("<!-- Created with HTMLGenerator https://github.com/nicholasdry/HTMLGenerator -->");
		output.println();

		// adds the title of the webpage
		output.printf("<title>%s</title>", html.getTitle());
		output.println();
                
                // adds the css to the webpage
                output.printf("<link rel='stylesheet/css' href='%s'>", html.getCSS(), html.getTitle());
		output.println();

		// adds the header of the page
		output.printf("<h1>%s</h1>", html.getHeader());
		output.println();

		// add the paragraph text of the webpage
		output.printf("<p>%s</p>", html.getParagraph());
		output.println();

		// add the footer of the webpage
		output.printf("<footer>%s</footer>", html.getFooter());
		output.println();
		output.println();

		output.write("</html>");

                output.close();

	}
    
    private static void exportHTMLFormatted(PrintWriter output) {
                output.println("<html>");
		output.println();

		// adds in copyright info
		output.println("<!-- Created with HTMLGenerator https://github.com/nicholasdry/HTMLGenerator -->");
		output.println();

		// adds the title of the webpage
		output.printf("<title>%s</title>", html.getTitle());
		output.println();
                
                // adds the css to the webpage
                output.printf("<link rel='stylesheet/css' href='%s'>%s</link>", html.getCSS(), html.getTitle());
		output.println();

		// adds the header of the page
		output.printf("<h1>%s</h1>", html.getHeader());
		output.println();

		// add the paragraph text of the webpage
		output.printf("%s", html.getParagraph());
		output.println();

		// add the footer of the webpage
		output.printf("<footer>%s</footer>", html.getFooter());
		output.println();
		output.println();

		output.write("</html>");

                output.close();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCSS;
    private javax.swing.JFrame addCSSWindow;
    private javax.swing.JMenuItem addJS;
    private javax.swing.JFrame addJSWindow;
    private javax.swing.JButton cssAddButton;
    private javax.swing.JTextField cssFileField;
    private javax.swing.JLabel cssFileName;
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem fileClose;
    private javax.swing.JTextField fileName;
    private javax.swing.JLabel fileNameTag;
    private javax.swing.JMenuItem fileNew;
    private javax.swing.JLabel footerText;
    private javax.swing.JTextField footerTextField;
    private javax.swing.JLabel headerText;
    private javax.swing.JTextField headerTextField;
    private javax.swing.JMenu help;
    private javax.swing.JFrame helpWindow;
    private javax.swing.JCheckBox htmlFormatting;
    private javax.swing.JMenuItem htmlTagGuide;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jsAddButton;
    private javax.swing.JTextField jsFileField;
    private javax.swing.JLabel jsFileName;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JScrollPane paragraphScollPane;
    private javax.swing.JLabel paragraphText;
    private javax.swing.JTextArea paragraphTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel titleText;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
